version: '3.9'

services:

  webserver:
    image: apache/airflow:2.6.0-python3.9
    command: webserver
    entrypoint: ["bash", "-c", "/opt/airflow/entrypoint.sh"]
    depends_on:
      - postgres
    environment:
      - LOAD_EX=n
      - EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql://airflow:airflow@postgres:5432/airflow
      - AIRFLOW__WEBSERVER__SECRET_KEY=this_is_a_very_secured_key
      - _AIRFLOW_DB_UPGRADE=True
      - GOOGLE_APPLICATION_CREDENTIALS=/opt/airflow/gcp/service-account.json
    logging:
      options:
        max-size: 10m
        max-file: "3"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./entrypoint.sh:/opt/airflow/entrypoint.sh
      - ./requirements.txt:/opt/airflow/requirements.txt
      - ./gcp/service-account.json:/opt/airflow/gcp/service-account.json:ro
    ports:
      - "8080:8080"
    healthcheck:
      test: ['CMD-SHELL', "[-f /opt/airflow/airflow-webserver.pid ]"]
      interval: 600s
      timeout: 600s
      retries: 3
    networks:
      - confluent

  scheduler:
    image: apache/airflow:2.6.0-python3.9
    depends_on:
      webserver:
        condition: service_healthy
    volumes:
      - ./dags:/opt/airflow/dags
      - ./entrypoint.sh:/opt/airflow/entrypoint.sh
      - ./requirements.txt:/opt/airflow/requirements.txt
      - ./gcp/service-account.json:/opt/airflow/gcp/service-account.json:ro
    environment:
      - LOAD_EX=n
      - EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql://airflow:airflow@postgres:5432/airflow
      - AIRFLOW__WEBSERVER__SECRET_KEY=this_is_a_very_secured_key
      - GOOGLE_APPLICATION_CREDENTIALS=/opt/airflow/gcp/service-account.json
    command: bash -c "pip install -r ./requirements.txt && airflow db upgrade && airflow scheduler"
    networks:
      - confluent

  postgres:
    image: postgres:14.0
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
    logging:
      options:
        max-size: 10m
        max-file: "3"
    networks:
      - confluent

networks:
  confluent:
